---
title: Jekylltest
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Jekyll Test
description: Test bed for understanding Jekyll
avatar: https://avatars1.githubusercontent.com/u/1193010?s=460&v=4
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: davidthompson/jekylltest
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: https://davidthompson.github.io/jekylltest
baseurl: "/jekylltest"
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
